spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        - id: order
          uri: http://localhost:8085
          predicates:
            - Path=/order/**
        - id: customer
          uri: http://localhost:8084
          predicates:
            - Path=/customer/**
        - id: product
          uri: http://localhost:8086
          predicates:
            - Path=/productredis/**
        - id: spring_boot_api_jwt_ad-refresh_token_branch
          uri: http://localhost:8080
          predicates:
            - Path=/spring_boot_api_jwt_ad-refresh_token_branch/**